### ISSUE TITLE
Express middleware `express-error-slack` doesn't work with NestJS, but works for express server

### ISSUE THREAD

**Issue by blitzmann** [nestjs/docs.nestjs.com#691] opened 2019-09-17 13:00 UTC
## Current behavior
NestJS documentation explains that nest Middleware is the same as express middleware. However, when trying to use the `express-error-slack` middleware, it seems the function never gets called. This doesn't seem to be a problem with the package itself, since the same package works as expected in express

https://github.com/chunkai1312/express-error-slack

## Input Code

main.ts:
```ts

import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { ValidationPipe } from '@nestjs/common';
import * as helmet from 'helmet';
import * as expressslack from 'express-error-slack';

async function bootstrap() {
    const app = await NestFactory.create(AppModule);
    app.useGlobalPipes(new ValidationPipe());
    app.use(expressslack({ webhookUri: 'webhookURL' }));
    app.use(helmet());
    await app.listen(3000);
}
bootstrap();
```
Controller

```ts

@Controller()
export class MyController {
    @Get('error')
    async error() {
        throw new Error('Error!');
    }
}
```

I would expect the express slack middleware to pick up the error and handle it, but it's not 

## Environment

Nest version: 6
 
For Tooling issues:
- Node version: 10.15.1
- Platform:  Windows 10

**Comment by kamilmysliwiec** [comment] 2019-09-23 16:20
Thanks for the suggestion! I think we should add to the docs that it's recommended to use more Nest-ish version of handling errors (using filters/interceptors/throwing exceptions) instead of passing an instance of the error to `next()` function.

**Comment by kamilmysliwiec** [comment] 2019-09-30 11:30
It's actually a duplicate of this https://github.com/nestjs/docs.nestjs.com/issues/215

**Closed by kamilmysliwiec** 2019-09-30 11:30 UTC
Labels: content, type: improvement
