### ISSUE TITLE
Guideline for referencing a third-party tool in the docs

### ISSUE THREAD

**Issue by clement-estone** [nestjs/docs.nestjs.com#2229] opened 2022-02-28 09:26 UTC
Hi! I'm Clément, a developer working at web agency named [LoneStone](https://lonestone.io/).

We use Nest.js daily for both our internal and external projects, and really enjoy this framework. As we often work with REST APIs, we've recently published a tool named the [SDK generator][https://github.com/lonestone/nest-sdk-generator), which is a tool designed to build a strongly-typed SDK from a Nest.js REST API server. It's entirely free and open-source.

We think it could be useful to a number of persons, so we'd like to know if it'd be possible to reference it in the docs, to get more exposure on it and detail how to use it directly in Nest.js' documentation.

If it is, please tell me how I should proceed - should I open a PR and create a new entry in the Recipes section? Just like the image below:

![image](https://user-images.githubusercontent.com/73881870/155958045-8e790461-a0d9-4042-b753-b347669f3f16.png)

Thanks in advance for your help!

**Comment by micalevisk** [comment] 2022-02-28 10:56
you can add it to https://github.com/nestjs/awesome-nestjs list at least

**Comment by clement-estone** [comment] 2022-02-28 13:54
Good idea, I've opened a PR on the repository :)

**Comment by Tony133** [comment] 2023-01-05 15:38
This issue is a duplicate of this issue https://github.com/nestjs/docs.nestjs.com/issues/519 which we could both close since there is the reference repository https://github.com/nestjs/awesome-nestjs , no ?

**Closed** 2024-10-18 07:47 UTC
