### ISSUE TITLE
Authorization: integration or example

### ISSUE THREAD

**Issue by amesas** [nestjs/docs.nestjs.com#228] opened 2019-01-11 09:09 UTC
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[x] Feature request
[x] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

Missing examples and/or feature. 

## Expected behavior

Integrated authorization or  an example for advanced authorization.

## What is the motivation / use case for changing the behavior?

For more complex apps Authentication isn't enough, an Authorization is a needed.
Getting a documented/example/defined pattern for Authorization could be a great starting point.
And maybe an integrated package?
We are experimenting with
https://github.com/casbin/casbin
https://github.com/open-policy-agent/opa 
But would prefer an opinionated way to do it.

**Comment by kamilmysliwiec** [comment] 2019-02-03 21:08
Sounds like duplicate of:
https://github.com/nestjs/docs.nestjs.com/issues/99
https://github.com/nestjs/docs.nestjs.com/issues/75

We're working on it.

**Comment by amesas** [comment] 2019-02-04 05:58
@kamilmysliwiec Not authentication, but authorization.

Examples, a few of them are simple, others don't:

- Only allow edit owned data, but view the data for my team, not being able to see other data. (GraphQL / Database ).
- Access only from a few IPs (by Policy).
- Simulate a full RBAC model.

A few real examples:

- https://github.com/casbin/node-casbin/tree/master/examples
- https://www.openpolicyagent.org/ (scroll down on homepage)

We are doing some initial tests with OPA, as it could be integrated with all our services, but a good and opinionated pattern on how to do it, could cover a big "missing" area in Nest.

**Comment by kamilmysliwiec** [comment] 2019-02-04 07:20
Well, I misread the title. Let's keep this open then

**Comment by joe307bad** [comment] 2019-02-06 01:40
hey @amesas, here is an example of an access control layer (ACL) I built using NestJS and [accesscontrol](https://github.com/onury/accesscontrol)

https://github.com/joe307bad/points/tree/master/API.Points/src/core/acl

**Closed** 2021-01-20 10:36 UTC
Labels: content, type: tutorial
